platform :ios, '10.0'

target 'GMChainSm2Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMChainSm2Example
	# pod 'GMChainSm2', path: => '../'

	pod 'GMChainSm2', :path => '../'

  pod 'Moya'
  pod 'CocoaDebug', :configuration => ['Debug']
  
end
